-- AlterTable
ALTER TABLE "banners_thumbnail" ADD COLUMN     "lg_key" TEXT NOT NULL DEFAULT 'LG_AWSBUCKET',
ADD COLUMN     "md_key" TEXT NOT NULL DEFAULT 'MD_AWSBUCKET',
ADD COLUMN     "sm_key" TEXT NOT NULL DEFAULT 'SM_AWSBUCKET';
